# Matrizenmultiplikation

## Theorie

In [2]:
import numpy as np
import sympy as sp
import matplotlib.pyplot as plt

In [9]:
A = np.array ([[1,2,3], [4,5,6]])
B = np.array ([[1,4,7,10], [2,5,8,11], [3,6,9,12]])
C = np.array ([[1,0,1], [0,1,0]])

# Möglichkeit 1:
AB_1 = np.dot(A, B)

# Möglichkeit 2:
AB_2 = A.dot(B)

# Möglichkeit 3: (Python >3.5)
AB_3 = A @ B

AB_3


array([[ 14,  32,  50,  68],
       [ 32,  77, 122, 167]])

In [15]:
# Elementweise Multiplikation
AC = A * C

AC

# Funktioniert nicht...:
# AB_4 = A * B
# np.dot(A, C)

array([[1, 0, 3],
       [0, 5, 0]])

## Aufgabe 9
\begin{vmatrix}
 x_1 + 5x_2 + 4x_3 + x_4 &= 6 \\
5x_1 + 11x_2 + 8x_3 + 2_4 &= 13 \\
3x_1 + 13x_2 + 11x_3 + 2x_4 &= 15 \\
-x_1 + x_2 + x_3 + x_4 &= 1 \\
\end{vmatrix}

In [48]:
# Aufgabe a
Ahat = np.array([ [1,5,4,1,6],
                [5,11,8,2,13],
                [3,13,11,2,15],
                [-1,1,1,1,1] ])



A rank: 4


In [52]:
RZF, _ = sp.Matrix(Ahat).rref()
RZF

Matrix([
[1, 0, 0, 0, -1/2],
[0, 1, 0, 0,  5/2],
[0, 0, 1, 0, -4/3],
[0, 0, 0, 1, -2/3]])

In [55]:
print ("A rank: " + str(Arank))

A rank: 4


## Aufgabe 10

### a)
$$
A = [a_{ij}]_{1 \leq i \leq 2,1 \leq j \leq 10}
$$
mit 
$$
a_{ij} = 
\begin{cases}
\phantom{} i & \text{für } i = 1\\
           i^{2} & \text{für } i = 2
\end{cases}
$$
A sei eine 2x10 Matrix


In [6]:
A = np.zeros((2,10))
for i in range(0,2):
    for j in range(0,10):
        if i == 0:
            A[i,j] = i+1
        else:
            A[i,j] = (i+1)**2

print (A)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [4. 4. 4. 4. 4. 4. 4. 4. 4. 4.]]


### b)
$$
B = [b_{ij}]_{1 \leq i,j \leq 6}
$$
mit 
$$
b_{ij} = 
\begin{cases}
\phantom{} \quad 0 & \text{für } i = j\\
           i+j & \text{für } i < j\\
           i-j & \text{für } i > j
\end{cases}
$$

B sei eine 6x6 Matrix

In [5]:
B = np.zeros((6,6))

for i in range(0,6):
    for j in range(0,6):
        if i == j:
            B[i,j] = 0
        elif i < j:
            B[i,j] = (i+1) + (j+1)
        else:
            B[i,j] = (i+1) - (j+1)

print (B)

[[ 0.  3.  4.  5.  6.  7.]
 [ 1.  0.  5.  6.  7.  8.]
 [ 2.  1.  0.  7.  8.  9.]
 [ 3.  2.  1.  0.  9. 10.]
 [ 4.  3.  2.  1.  0. 11.]
 [ 5.  4.  3.  2.  1.  0.]]


### c)
$$
C = [c_{ij}]_{1 \leq i,j \leq 5}
$$
mit 
$$
c_{ij} = 
\begin{cases}
\phantom{} 0 & \text{für } i+j < 6\\
           1 & \text{für } i+j = 6\\
           2 & \text{für } i + j > 6
\end{cases}
$$

C sei eine 5x5 Matrix

In [9]:
C = np.zeros((5,5))

for i in range(0,5):
    for j in range(0,5):
        if i + j < 4:
            C[i,j] = 0
        elif i + j == 4:
            C[i,j] = 1
        else:
            C[i,j] = 2

print(C)

[[0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 2.]
 [0. 0. 1. 2. 2.]
 [0. 1. 2. 2. 2.]
 [1. 2. 2. 2. 2.]]


## Aufgabe 11

Aufgabe 2(e) mit Numpy:
$$
\begin{pmatrix}
1 & 2 \\
0 & 1
\end{pmatrix}^n
\quad \text{für n} \in \mathbb{N}
$$

$$n^{10} \text{ = ?}$$

In [15]:
A = [[1,2],[0,1]]
Apow = np.linalg.matrix_power(A, 10)

print(Apow)

[[ 1 20]
 [ 0  1]]


dasselbe mit sympy:

In [17]:
A = sp.Matrix([[1,2],[0,1]])
A**10

Matrix([
[1, 20],
[0,  1]])