In [2]:
import numpy as np
import sympy as sp
import matplotlib.pyplot as plt

# Übung 6
## Aufgabe 11

### a)
$$
\vec{a}=\begin{pmatrix}
5\\ 2\\ 3
\end{pmatrix},
\quad
\vec{b}=\begin{pmatrix}
7\\ 4\\ 2
\end{pmatrix},
\quad
\vec{c}=\begin{pmatrix}
-2\\ 5\\ 8
\end{pmatrix}
\quad
\vec{d}=\begin{pmatrix}
-3\\ -2\\ 1
\end{pmatrix}
\quad
\vec{e}=\begin{pmatrix}
0\\ 1\\ 0
\end{pmatrix}
$$

In [13]:
a = np.array([[5], [2], [3]])
b = np.array([[7], [4], [2]])
c = np.array([[-2], [5], [8]])
d = np.array([[-3], [-2], [1]])
e = np.array([[0], [1], [0]])

a+b

array([[12],
       [ 6],
       [ 5]])

In [14]:
c-(2*d - 4*e)

array([[ 4],
       [13],
       [ 6]])

In [15]:
a + (b-a) + (c-b)

array([[-2],
       [ 5],
       [ 8]])

### b)

In [ ]:
k, x, y, z = sp.symbols('k x y z', real=True)
